// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    partial class AnimalShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 2,
                            Name = "Spooky",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 3,
                            Name = "Alexa",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 5,
                            Name = "Beethoven",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 1,
                            Name = "Bella",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 4,
                            Name = "Blake",
                            Type = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
